Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: aws_serverless_downloader_userpool
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - AttributeDataType: String
          DeveloperOnlyAttribute: false
          Mutable: true
          Name: email
          Required: true

  HealthCheckLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: HealthCheckLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: HealthCheckLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:GET
                Resource:
                  - "arn:aws:apigateway:us-east-1::/restapis/*/stages/dev/GET/healthCheck"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - "arn:aws:lambda:us-east-1:1234567890:function:etl-multiplexor-template-dev-healthCheck"

  ToUpperCaseLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ToUpperCaseLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ToUpperCaseLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:POST
                Resource:
                  - "arn:aws:apigateway:us-east-1::/restapis/*/stages/dev/POST/toUpperCase"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - "arn:aws:lambda:us-east-1:1234567890:function:etl-multiplexor-template-dev-toUpperCase"

  EatPayloadLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EatPayloadLambdaRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: EatPayloadLambdaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - apigateway:POST
                Resource:
                  - "arn:aws:apigateway:us-east-1::/restapis/*/stages/dev/POST/eatPayload"
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - "arn:aws:lambda:us-east-1:1234567890:function:etl-multiplexor-template-dev-eatPayload"
