service: etl-multiplexor-template
provider:
  name: aws
  runtime: java8
  stage: dev
  timeout: 30
  region: us-east-1
  memorySize: 3008
package:
  individually: true
functions:
  healthCheck:
    package:
      artifact: target/multiplexor-template-0.0.1-SNAPSHOT-healthCheck.jar
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    events:
      - http:
          path: /healthCheck
          method: GET
          cors: false
    environment:
      FUNCTION_NAME: healthCheck

  toUpperCase:
    package:
      artifact: target/multiplexor-template-0.0.1-SNAPSHOT-toUpperCase.jar
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    events:
      - http:
          path: /toUpperCase
          method: POST
          cors: false
    environment:
      FUNCTION_NAME: toUpperCase

  eatPayload:
    package:
      artifact: target/multiplexor-template-0.0.1-SNAPSHOT-eatPayload.jar
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    events:
      - http:
          path: /eatPayload
          method: POST
          cors: false
    environment:
      FUNCTION_NAME: eatPayload

#service: etl-multiplexor-template
#provider:
#  name: aws
#  runtime: java8
#  stage: dev
#  timeout: 30
#  region: us-east-1
#  memorySize: 3008
#package:
#  individually: true
#functions:
#  healthCheck:
#    package:
#      artifact: target/multiplexor-template-0.0.1-SNAPSHOT-healthCheck.jar
#    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
#    events:
#      - http:
#          path: /healthCheck
#          method: GET
#          cors: false
#    environment:
#      FUNCTION_NAME: healthCheck
#    iamRoleStatements:
#      - Effect: Allow
#        Action:
#          - apigateway:GET
#        Resource:
#          - "arn:aws:apigateway:us-east-1::/restapis/*/stages/dev/GET/healthCheck"
#      - Effect: Allow
#        Action:
#          - lambda:InvokeFunction
#        Resource:
#          - "arn:aws:lambda:us-east-1:1234567890:function:etl-multiplexor-template-dev-healthCheck"
#
#  toUpperCase:
#    package:
#      artifact: target/multiplexor-template-0.0.1-SNAPSHOT-toUpperCase.jar
#    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
#    events:
#      - http:
#          path: /toUpperCase
#          method: POST
#          cors: false
#    environment:
#      FUNCTION_NAME: toUpperCase
#    iamRoleStatements:
#      - Effect: Allow
#        Action:
#          - apigateway:POST
#        Resource:
#          - "arn:aws:apigateway:us-east-1::/restapis/*/stages/dev/POST/toUpperCase"
#      - Effect: Allow
#        Action:
#          - lambda:InvokeFunction
#        Resource:
#          - "arn:aws:lambda:us-east-1:1234567890:function:etl-multiplexor-template-dev-toUpperCase"
#
#  eatPayload:
#    package:
#      artifact: target/multiplexor-template-0.0.1-SNAPSHOT-eatPayload.jar
#    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
#    events:
#      - http:
#          path: /eatPayload
#          method: POST
#          cors: false
#    environment:
#      FUNCTION_NAME: eatPayload
#    iamRoleStatements:
#      - Effect: Allow
#        Action:
#          - apigateway:POST
#        Resource:
#          - "arn:aws:apigateway:us-east-1::/restapis/*/stages/dev/POST/eatPayload"
#      - Effect: Allow
#        Action:
#          - lambda:InvokeFunction
#        Resource:
#          - "arn:aws:lambda:us-east-1:1234567890:function:etl-multiplexor-template-dev-eatPayload"
